### ISSUE TITLE
Criar vagas do estacionamento. (Front)

### ISSUE THREAD

**Issue by joseRibamar21** [ES2-UFPI/iparking#31]
Telas de manipulaçao de vagas.

**Comment by TitusAwakes** [comment]
Finalizar até quinta-feira (08/09)

**Comment by TitusAwakes** [comment]
[f664bdd](https://github.com/ES2-UFPI/iparking/commit/f664bdd1bf4a8cbd93a885432f6878e0545da6a8) corrige a declaração do checkbox.
